#!/usr/bin/python3
import plogpy
import pprint
import pandas as pd

def plot_df(df):
    ax = df.plot(kind='area', stacked=True, alpha=0.4)
    fig = ax.get_figure()
    fig.savefig('zzz.png')

if __name__ == '__main__':
    d = plogpy.parse_log("log_sample/dstat.log")
    for k, v in d.items():
        print(k)
        print(v)
    

    d = plogpy.parse_log("log_sample/sar_u.log")
    for k, v in d.items():
        print(k,v)

    d = plogpy.parse_log("log_sample/sar_u_ALL.log")
    for k, v in d.items():
        print(k,v)

    d = plogpy.parse_log("log_sample/sar_P_ALL.log")
    for k, v in d.items():
        print(k)
        print(v)
        plot_df(v)
        break